//
// Created by Magida on 05-11-2018.
//

#ifndef THEMAZE_DEFINITIONS_H
#define THEMAZE_DEFINITIONS_H

//ALL MACROS THAY IS USED IN THE PROJECT IS DEFINED HERE
#define CATCH_CONFIG_MAIN
#define FMT_HEADER_ONLY

#endif //THEMAZE_DEFINITIONS_H
